name: deployment

on:
  workflow_dispatch:

env:
  HOST: cassini.cs.kent.edu
  USER: diagonal
  TARGET: diagonal@cassini.cs.kent.edu
  RUN: ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no diagonal@cassini.cs.kent.edu
  COPY: scp -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  deploy_to_cassini:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_RSA }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Get the repo code
        uses: actions/checkout@v2
        with: 
          repository: gregdelozier/diagonal
      - name: Look at the files
        run: |
          echo $ ls -la 
          ls -la 
          echo $ pwd
          pwd
      - name: Ping the server
        run: |
          $RUN 'ls -la'
          echo "hello" >hello.txt
          $COPY hello.txt $TARGET:/home/diagonal
      - name: Copy code to server
        run: |
          $RUN 'mkdir -p /home/diagonal/web'
          $RUN 'rm -r /home/diagonal/web/*'
          $COPY index.html $TARGET:/home/diagonal/web
          $COPY sketch.js $TARGET:/home/diagonal/web
          $COPY style.css $TARGET:/home/diagonal/web
          $RUN 'ls -la /home/diagonal/web'
      
      - name: Start server process
        run: |
          # kill the 'screen
          # ssh $USER$@$HOST 'screen -S diagonal -X quit'
          $RUN 'screen -S diagonal -X quit' || true
          # ssh $TARGET 'screen -dmS myappname python -m http.server 9876'
          $RUN 'screen -dmS diagonal python -m http.server 9753'

      
        
      
      
          



